### ISSUE TITLE
Regarding Sceneform, multiple sfb conversion

### ISSUE THREAD

**Issue by ishaqtt** [ManuelTS/augmentedFaceMeshIndices#1]
Greetings Mr. Manuel , Could you able to convert multiple sfb from obj file? , as you described another repository. I have same situation here, can you help me?
I am using Android studio 3.5.3
                 Google sceneform Tools (Beta)  v. 1.14.0
                  Gradle  v.6.5

**Comment by ManuelTS** [comment]
Hi ishaqtt,

I don't have the original code anymore, but you can see some shell code which shows you the way to your own script on this comment
https://github.com/google-ar/sceneform-android-sdk/issues/217#issuecomment-412043632
and on the comments below.
