### ISSUE TITLE
Converting dlib points to mediapipe?

### ISSUE THREAD

**Issue by ghost** [ManuelTS/augmentedFaceMeshIndices#3]
I  have been using mediapipe to detect face landmarks on a single image, but I have an image that it will not detect the landmarks. Is there any possible way to specify the 5 dlib face landmarks and interpolate these to mediapipe's 468 landmarks in python?

Thanks!

**Comment by ManuelTS** [comment]
I only have few experience with Python and unfortunately for several years I do not have developed anything with AR core. So, here you are on the wrong address, sorry.
